### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by DepravityDame** [gxywy/jlu-health-report#3]
想请教下我按照README中教程设置好了，但是到了autocheck.yml中schedule设置的时间，工作流并没有执行，Actions里也是空的，想问下这种情况怎么处理呀

**Comment by gxywy** [comment]
![123](https://i.loli.net/2021/01/23/QEnyCXKJdzhtfj3.png)
需要手动在Actions界面中启动工作流

另外，这种模式不是很稳定，经常会出现打卡失败的情况，推荐还是直接使用本地脚本进行打卡

**Comment by gxywy** [comment]
![123.png](https://i.loli.net/2021/01/23/NxdocEB3tgPFsjL.png)
如果是空白则需要在Actions里需要点击绿色的按钮启用

**Comment by gxywy** [comment]
Github Actions相关bug已在[commit 2beb205](https://github.com/gxywy/jlu-health-report/commit/2beb20584bf5f843525062c74a652398e41427ac)中修复
