### ISSUE TITLE
HTTPSConnectionPool

### ISSUE THREAD

**Issue by DepravityDame** [gxywy/jlu-health-report#5]
作者大大
今天使用的时候发现一直提示
HTTPSConnectionPool(host='ehall.jlu.edu.cn', port=443): Max retries exceeded with url: /sso/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
Retrying...
按网上加
 s.keep_alive = False的方法
也无法解决，服务器上是这样，换到电脑上还是这样
想问下如何解决呀~

**Comment by gxywy** [comment]
感觉应该是设定的打卡时间(7点)恰好ehall.jlu.edu.cn崩了，或者此时打卡人数过多，服务器压力较大

**Comment by DepravityDame** [comment]
我在服务器用的计划任务，随机时间打卡的，我也考虑过网站崩溃情况，但是现在网站正常访问可以进去，运行脚本还是提醒这个

**Comment by gxywy** [comment]
相关bug已在[commit 0396f5e](https://github.com/gxywy/jlu-health-report/commit/0396f5e8189c5c8ba93937202dcc722fc2a4d9a8)中修复
