### ISSUE TITLE
Github Actions能多用户登录么？

### ISSUE THREAD

**Issue by gaohanga** [gxywy/jlu-health-report#6]
如题，请问这个大概是每天什么时间段打卡

**Comment by gxywy** [comment]
Github Actions暂不支持多用户，作为本地脚本使用支持多用户打卡
Github Actions打卡时间如下，可自行修改：
https://github.com/gxywy/jlu-health-report/blob/1be4ed009f7b96a6d791445b2d39a049d372a563/.github/workflows/autocheck.yml#L6
https://github.com/gxywy/jlu-health-report/blob/1be4ed009f7b96a6d791445b2d39a049d372a563/.github/workflows/autocheck.yml#L7

**Comment by gaohanga** [comment]
谢谢

**Comment by yangchenxiaa** [comment]
您好，请问如果想改成晚上8点触发。是cron: '0 13 * * *'改成cron: '0 0 20 * *'么？

**Comment by gxywy** [comment]
@yangchenxiaa 
将` cron: '0 13 * * *' `改为`cron: '0 12 * * *' `
